spring.application.name=netflix-gateway-service
spring.data.redis.host=localhost
spring.data.redis.port=6379

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyRuZrhtuHarHLGCws8BqFfY29aNF6NIWemIiB5tX796A+alXWA5PFGVDZWEeVCZKROuKFXNaft8Rb5pSvihwRjIcZpo097PUM8D4QD3f6ckt0PJCPb7HeDC7gQtf/Gv1apNn3VMEGHQiCX57YR+xc7SheUgDF3OkAU0+S3iwMhLnF41bNKdY0iaJreQ7cLpPZ7m4CbE39sQlJEIv02PwW4mrXSP9YonqcaHprGpzgvH7ySPwVljNIAVpn6ESUp9Un1iC+WcDtFtDhV69jogYBDROGRi54LMkgQKmAShv0//BIGU4hYV0x4kKEVpwfEuS+hK/3zDzjOpke3jEejcvJQIDAQAB